/*
 * Dojo K6 Ecommerce
 * Ecommerce utilizado no Dojo  ## Congratulations! Your application is ready.    Please note that all endpoints are secured with JWT Bearer authentication. By default, your app comes with one user with the username \"admin\" and password \"admin\".
 *
 * OpenAPI spec version: 0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * OpenAPI generator version: 6.1.0-SNAPSHOT
 */


import http from "k6/http";
import { group, check, sleep } from "k6";

const BASE_URL = "/";
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.

export default function() {
    group("/api/addresses", () => {
        let take = 'TODO_EDIT_THE_TAKE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let orderBy = 'TODO_EDIT_THE_ORDERBY'; // specify value as there is no example value for this parameter in OpenAPI spec
        let where = 'TODO_EDIT_THE_WHERE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let skip = 'TODO_EDIT_THE_SKIP'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/addresses?where=${where}&orderBy=${orderBy}&skip=${skip}&take=${take}`;
            let request = http.get(url);

            check(request, {
                "": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/api/addresses`;
            // TODO: edit the parameters of the request body.
            let body = {"address1": "string", "address2": "string", "city": "string", "customers": {"connect": "list"}, "state": "string", "zip": "bigdecimal"};
            let params = {headers: {"Content-Type": "application/json", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "": (r) => r.status === 201
            });
        }
    });

    group("/api/customers/{id}/orders", () => {
        let take = 'TODO_EDIT_THE_TAKE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let orderBy = 'TODO_EDIT_THE_ORDERBY'; // specify value as there is no example value for this parameter in OpenAPI spec
        let where = 'TODO_EDIT_THE_WHERE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let skip = 'TODO_EDIT_THE_SKIP'; // specify value as there is no example value for this parameter in OpenAPI spec
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/customers/${id}/orders?where=${where}&orderBy=${orderBy}&skip=${skip}&take=${take}`;
            let request = http.get(url);

            check(request, {
                "": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/api/customers/${id}/orders`;
            let params = {headers: {"Content-Type": "application/json", "Accept": "application/json"}};
            let request = http.patch(url, params);

            check(request, {
                "": (r) => r.status === 200
            });
        }
    });

    group("/api/users/{id}", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/users/${id}`;
            let request = http.get(url);

            check(request, {
                "": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/api/users/${id}`;
            // TODO: edit the parameters of the request body.
            let body = {"firstName": "string", "lastName": "string", "password": "string", "roles": "list", "username": "string"};
            let params = {headers: {"Content-Type": "application/json", "Accept": "application/json"}};
            let request = http.patch(url, JSON.stringify(body), params);

            check(request, {
                "": (r) => r.status === 200
            });
        }
    });

    group("/api/orders", () => {
        let take = 'TODO_EDIT_THE_TAKE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let orderBy = 'TODO_EDIT_THE_ORDERBY'; // specify value as there is no example value for this parameter in OpenAPI spec
        let where = 'TODO_EDIT_THE_WHERE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let skip = 'TODO_EDIT_THE_SKIP'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/orders?where=${where}&orderBy=${orderBy}&skip=${skip}&take=${take}`;
            let request = http.get(url);

            check(request, {
                "": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/api/orders`;
            // TODO: edit the parameters of the request body.
            let body = {"whereLeft_Square_BracketcustomerRight_Square_Bracket": {"id": "string"}, "discount": "bigdecimal", "whereLeft_Square_BracketproductRight_Square_Bracket": {"id": "string"}, "quantity": "bigdecimal", "totalPrice": "bigdecimal"};
            let params = {headers: {"Content-Type": "application/json", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "": (r) => r.status === 201
            });
        }
    });

    group("/api/addresses/{id}", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/addresses/${id}`;
            let request = http.get(url);

            check(request, {
                "": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/api/addresses/${id}`;
            // TODO: edit the parameters of the request body.
            let body = {"address1": "string", "address2": "string", "city": "string", "customers": {"connect": "list", "disconnect": "list", "set": "list"}, "state": "string", "zip": "bigdecimal"};
            let params = {headers: {"Content-Type": "application/json", "Accept": "application/json"}};
            let request = http.patch(url, JSON.stringify(body), params);

            check(request, {
                "": (r) => r.status === 200
            });
        }
    });

    group("/api/_health/live", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/_health/live`;
            let request = http.get(url);

            check(request, {
                "": (r) => r.status === 200
            });
        }
    });

    group("/api/addresses/{id}/customers", () => {
        let take = 'TODO_EDIT_THE_TAKE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let orderBy = 'TODO_EDIT_THE_ORDERBY'; // specify value as there is no example value for this parameter in OpenAPI spec
        let where = 'TODO_EDIT_THE_WHERE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let skip = 'TODO_EDIT_THE_SKIP'; // specify value as there is no example value for this parameter in OpenAPI spec
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/addresses/${id}/customers?where=${where}&orderBy=${orderBy}&skip=${skip}&take=${take}`;
            let request = http.get(url);

            check(request, {
                "": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/api/addresses/${id}/customers`;
            let params = {headers: {"Content-Type": "application/json", "Accept": "application/json"}};
            let request = http.patch(url, params);

            check(request, {
                "": (r) => r.status === 200
            });
        }
    });

    group("/api/products", () => {
        let take = 'TODO_EDIT_THE_TAKE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let orderBy = 'TODO_EDIT_THE_ORDERBY'; // specify value as there is no example value for this parameter in OpenAPI spec
        let where = 'TODO_EDIT_THE_WHERE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let skip = 'TODO_EDIT_THE_SKIP'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/products?where=${where}&orderBy=${orderBy}&skip=${skip}&take=${take}`;
            let request = http.get(url);

            check(request, {
                "": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/api/products`;
            // TODO: edit the parameters of the request body.
            let body = {"description": "string", "itemPrice": "bigdecimal", "name": "string", "orders": {"connect": "list"}};
            let params = {headers: {"Content-Type": "application/json", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "": (r) => r.status === 201
            });
        }
    });

    group("/api/login", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/login`;
            // TODO: edit the parameters of the request body.
            let body = {"username": "string", "password": "string"};
            let params = {headers: {"Content-Type": "application/json", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "": (r) => r.status === 201
            });
        }
    });

    group("/api/users", () => {
        let take = 'TODO_EDIT_THE_TAKE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let orderBy = 'TODO_EDIT_THE_ORDERBY'; // specify value as there is no example value for this parameter in OpenAPI spec
        let where = 'TODO_EDIT_THE_WHERE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let skip = 'TODO_EDIT_THE_SKIP'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/users?where=${where}&orderBy=${orderBy}&skip=${skip}&take=${take}`;
            let request = http.get(url);

            check(request, {
                "": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/api/users`;
            // TODO: edit the parameters of the request body.
            let body = {"firstName": "string", "lastName": "string", "password": "string", "roles": "list", "username": "string"};
            let params = {headers: {"Content-Type": "application/json", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "": (r) => r.status === 201
            });
        }
    });

    group("/api/customers/{id}", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/customers/${id}`;
            let request = http.get(url);

            check(request, {
                "": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/api/customers/${id}`;
            // TODO: edit the parameters of the request body.
            let body = {"whereLeft_Square_BracketaddressRight_Square_Bracket": {"id": "string"}, "email": "string", "firstName": "string", "lastName": "string", "orders": {"connect": "list", "disconnect": "list", "set": "list"}, "phone": "string"};
            let params = {headers: {"Content-Type": "application/json", "Accept": "application/json"}};
            let request = http.patch(url, JSON.stringify(body), params);

            check(request, {
                "": (r) => r.status === 200
            });
        }
    });

    group("/api/_health/ready", () => {

        // Request No. 1
        {
            let url = BASE_URL + `/api/_health/ready`;
            let request = http.get(url);

            check(request, {
                "": (r) => r.status === 200
            });
        }
    });

    group("/api/products/{id}/orders", () => {
        let take = 'TODO_EDIT_THE_TAKE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let orderBy = 'TODO_EDIT_THE_ORDERBY'; // specify value as there is no example value for this parameter in OpenAPI spec
        let where = 'TODO_EDIT_THE_WHERE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let skip = 'TODO_EDIT_THE_SKIP'; // specify value as there is no example value for this parameter in OpenAPI spec
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/products/${id}/orders?where=${where}&orderBy=${orderBy}&skip=${skip}&take=${take}`;
            let request = http.get(url);

            check(request, {
                "": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/api/products/${id}/orders`;
            let params = {headers: {"Content-Type": "application/json", "Accept": "application/json"}};
            let request = http.patch(url, params);

            check(request, {
                "": (r) => r.status === 200
            });
        }
    });

    group("/api/orders/{id}", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/orders/${id}`;
            let request = http.get(url);

            check(request, {
                "": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/api/orders/${id}`;
            // TODO: edit the parameters of the request body.
            let body = {"whereLeft_Square_BracketcustomerRight_Square_Bracket": {"id": "string"}, "discount": "bigdecimal", "whereLeft_Square_BracketproductRight_Square_Bracket": {"id": "string"}, "quantity": "bigdecimal", "totalPrice": "bigdecimal"};
            let params = {headers: {"Content-Type": "application/json", "Accept": "application/json"}};
            let request = http.patch(url, JSON.stringify(body), params);

            check(request, {
                "": (r) => r.status === 200
            });
        }
    });

    group("/api/customers", () => {
        let take = 'TODO_EDIT_THE_TAKE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let orderBy = 'TODO_EDIT_THE_ORDERBY'; // specify value as there is no example value for this parameter in OpenAPI spec
        let where = 'TODO_EDIT_THE_WHERE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let skip = 'TODO_EDIT_THE_SKIP'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/customers?where=${where}&orderBy=${orderBy}&skip=${skip}&take=${take}`;
            let request = http.get(url);

            check(request, {
                "": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/api/customers`;
            // TODO: edit the parameters of the request body.
            let body = {"whereLeft_Square_BracketaddressRight_Square_Bracket": {"id": "string"}, "email": "string", "firstName": "string", "lastName": "string", "orders": {"connect": "list"}, "phone": "string"};
            let params = {headers: {"Content-Type": "application/json", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "": (r) => r.status === 201
            });
        }
    });

    group("/api/products/{id}", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/api/products/${id}`;
            let request = http.get(url);

            check(request, {
                "": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/api/products/${id}`;
            // TODO: edit the parameters of the request body.
            let body = {"description": "string", "itemPrice": "bigdecimal", "name": "string", "orders": {"connect": "list", "disconnect": "list", "set": "list"}};
            let params = {headers: {"Content-Type": "application/json", "Accept": "application/json"}};
            let request = http.patch(url, JSON.stringify(body), params);

            check(request, {
                "": (r) => r.status === 200
            });
        }
    });

}
